### ISSUE TITLE
Error: no time information in ""

### ISSUE THREAD

**Issue by alexbardas** [universal-ctags/homebrew-universal-ctags#16]
`macOS version`: 10.12.2
`brew --version`: Homebrew 1.1.7

```shell
❯❯❯ brew install --HEAD universal-ctags
==> Installing universal-ctags from universal-ctags/universal-ctags
==> Cloning https://github.com/universal-ctags/ctags.git
Removing invalid repository from cache
Cloning into '/Users/***/Library/Caches/Homebrew/universal-ctags--git'...
remote: Counting objects: 3078, done.
remote: Compressing objects: 100% (2583/2583), done.
remote: Total 3078 (delta 127), reused 2569 (delta 97), pack-reused 0
Receiving objects: 100% (3078/3078), 1.41 MiB | 551.00 KiB/s, done.
Resolving deltas: 100% (127/127), done.
Checking connectivity... done.
==> Checking out branch master
Error: no time information in ""
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/time.rb:327:in `parse'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:637:in `source_modified_time'
/usr/local/Homebrew/Library/Homebrew/resource.rb:96:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:94:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:86:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1893:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1125:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:112:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'
```

Any ideas what can go wrong?

**Comment by KazuakiM** [comment]
@alexbardas 
Can you tell me about the progress on this?
